import 'babel-polyfill';
import _ from 'lodash';
import 'material-design-lite/material.min.js';
import 'material-design-lite/material.min.css';
import 'material-design-icons/iconfont/material-icons.css';
import angular from 'angular';
import '../js/app';
import './../styles.less';
import '../js/sections/assistant/assistant';
import '../js/sections/configurator/configurator';
